# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:7.0
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - "mongo"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/products/node_modules

    env_file:
      - ./products/.env

  users:
    build:
      dockerfile: Dockerfile
      context: ./users
    container_name: users
    ports:
      - "4002:4002"
    restart: always
    depends_on:
      - "mongo"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/users/node_modules

    env_file:
      - ./users/.env

  orders:
    build:
      dockerfile: Dockerfile
      context: ./orders
    container_name: orders
    ports:
      - "4001:4001"
    restart: always
    depends_on:
      - "mongo"
      - "rabbitmq"
    volumes:
      - .:/app
      - /app/orders/node_modules

    env_file:
      - ./orders/.env

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./Proxy
    depends_on:
      - products
      - users
      - orders
    ports:
      - 80:80
      
volumes:
  db: